"""
Reads from single static/dynamic files generated by the new generator.
"""

import json
import math
import struct
import base64
import time
import numpy as np
from PIL import Image
from scipy.spatial import cKDTree
from typing import List, Dict, Tuple, Optional


# ============================================================
# PROGRESS BAR
# ============================================================

class ProgressBar:
    def __init__(self, total: int, desc: str = "Progress", width: int = 50):
        self.total = total
        self.desc = desc
        self.width = width
        self.current = 0
        self.start_time = time.time()
        self.last_print = 0
        
    def update(self, n: int = 1):
        self.current += n
        if self.current - self.last_print >= max(1, self.total // 100) or self.current >= self.total:
            self.print_bar()
            self.last_print = self.current
    
    def print_bar(self):
        percent = self.current / self.total if self.total > 0 else 1
        filled = int(self.width * percent)
        bar = "█" * filled + "░" * (self.width - filled)
        
        elapsed = time.time() - self.start_time
        if percent > 0 and percent < 1:
            eta = elapsed / percent - elapsed
            eta_str = f"ETA: {eta:.1f}s"
        else:
            eta_str = "Done!    "
        
        print(f"\r{self.desc}: |{bar}| {percent*100:5.1f}% ({self.current:,}/{self.total:,}) {eta_str}", end="", flush=True)
        
        if self.current >= self.total:
            print()
    
    def close(self):
        if self.current < self.total:
            self.current = self.total
            self.print_bar()


# ============================================================
# CONFIGURATION
# ============================================================

# Unified file names (from new generator)
STATIC_FILE = "tiles_static.json"
DYNAMIC_FILE = "tiles_dynamic.json"
METADATA_FILE = "tiles_metadata.json"

# Render settings
IMAGE_HEIGHT = 4096
IMAGE_WIDTH = IMAGE_HEIGHT * 2
RENDER_MODE = "type"  # "type" or "random" or "population"

if RENDER_MODE == "type":
    OUTPUT_FILE = "world_type.png"
elif RENDER_MODE == "random":
    OUTPUT_FILE = "world_random.png"
elif RENDER_MODE == "population":
    OUTPUT_FILE = "world_population.png"
else:
    print("Incorrect RENDER_MODE")
    import sys
    sys.exit()

# Filter which types to render
RENDER_LAND = True
RENDER_COASTAL = True
RENDER_DEEP_SEA = True

# Colors for type-based rendering
TYPE_COLORS = {
    "land": (34, 139, 34),      # Forest green
    "coastal": (135, 206, 235),  # Sky blue
    "deep_sea": (25, 25, 112),   # Midnight blue
    "unknown": (89, 89, 89)       # Gray
}

# Population color gradient (low to high population)
POPULATION_COLORS = [
    (25, 25, 112),   # Deep blue (low pop)
    (65, 105, 225),  # Royal blue
    (135, 206, 235), # Sky blue
    (144, 238, 144), # Light green
    (34, 139, 34),   # Forest green
    (255, 255, 0),   # Yellow
    (255, 165, 0),   # Orange
    (255, 0, 0)      # Red (high pop)
]


# ============================================================
# UTILITIES
# ============================================================

def decode_neighbors(encoded: str) -> list:
    """Decode base64 encoded neighbors."""
    if not encoded:
        return []
    binary = base64.b64decode(encoded)
    count = len(binary) // 4
    return list(struct.unpack(f"<{count}I", binary))

def load_tiles() -> Tuple[List[dict], dict]:
    """Load all tiles from unified files."""
    print("Loading unified tile files...")
    
    # Load metadata first
    try:
        with open(METADATA_FILE, "r") as f:
            metadata = json.load(f)
        print(f"  Metadata loaded:")
        print(f"    Total tiles: {metadata.get('total_tiles', 0):,}")
        print(f"    Base points: {metadata.get('base_points', 0):,}")
        print(f"    Sampling rates: {metadata.get('sampling_rates', {})}")
        print(f"    Tiles by type: {metadata.get('tiles_by_type', {})}")
    except FileNotFoundError:
        print(f"  Warning: {METADATA_FILE} not found")
        metadata = {}
    except json.JSONDecodeError:
        print(f"  Warning: {METADATA_FILE} is corrupted")
        metadata = {}
    
    # Load static data
    try:
        with open(STATIC_FILE, "r") as f:
            static_data = json.load(f)
        print(f"  Loaded {len(static_data):,} tiles from {STATIC_FILE}")
    except FileNotFoundError:
        print(f"  ERROR: {STATIC_FILE} not found")
        return [], {}
    except json.JSONDecodeError:
        print(f"  ERROR: {STATIC_FILE} is corrupted")
        return [], {}
    
    # Load dynamic data
    try:
        with open(DYNAMIC_FILE, "r") as f:
            dynamic_data = json.load(f)
        print(f"  Loaded {len(dynamic_data):,} entries from {DYNAMIC_FILE}")
    except FileNotFoundError:
        print(f"  Warning: {DYNAMIC_FILE} not found, using defaults")
        dynamic_data = []
    except json.JSONDecodeError:
        print(f"  Warning: {DYNAMIC_FILE} is corrupted, using defaults")
        dynamic_data = []
    
    # Build dynamic lookup
    dyn_lookup = {item["id"]: item for item in dynamic_data}
    
    # Combine static and dynamic data
    tiles = []
    filter_flags = {
        "land": RENDER_LAND,
        "coastal": RENDER_COASTAL,
        "deep_sea": RENDER_DEEP_SEA
    }
    
    bar = ProgressBar(len(static_data), "  Loading tiles")
    
    for s in static_data:
        tile_type = s.get("type", "unknown")
        
        # Filter by type
        if not filter_flags.get(tile_type, False):
            bar.update(1)
            continue
        
        tid = s["id"]
        d = dyn_lookup.get(tid, {})
        
        tiles.append({
            "id": tid,
            "type": tile_type,
            "neighbors": decode_neighbors(s.get("neighbors_b64", "")),
            "temperature": s.get("temperature", ""),
            "precipitation": s.get("precipitation", ""),
            "terrain": s.get("terrain", ""),
            "vegetation": d.get("vegetation", ""),
            "population": d.get("population", 0),
            "buildings": d.get("buildings", [])
        })
        bar.update(1)
    
    bar.close()
    
    # Sort by ID for consistent ordering
    tiles.sort(key=lambda t: t["id"])
    
    print(f"\n  Loaded {len(tiles):,} tiles after filtering")
    
    return tiles, metadata


# ============================================================
# FIBONACCI SPHERE & POSITIONS
# ============================================================

def fibonacci_sphere(samples: int) -> np.ndarray:
    """Generate Fibonacci sphere points as numpy array."""
    phi = (1 + math.sqrt(5)) / 2
    golden_angle = 2 * math.pi / phi
    i = np.arange(samples)
    y = 1 - (2*i + 1) / samples
    radius = np.sqrt(1 - y*y)
    theta = golden_angle * i
    x = np.cos(theta) * radius
    z = np.sin(theta) * radius
    return np.column_stack((x, y, z))

def regenerate_positions(tiles: List[dict], total_points: int):
    """Regenerate positions for all tiles."""
    if not tiles:
        return
    
    print(f"  Regenerating positions for {len(tiles):,} tiles...")
    positions = fibonacci_sphere(total_points)
    
    bar = ProgressBar(len(tiles), "  Assigning positions")
    
    missing = 0
    for tile in tiles:
        idx = tile["id"]
        if idx < total_points:
            tile["x"], tile["y"], tile["z"] = positions[idx]
        else:
            missing += 1
            tile["x"], tile["y"], tile["z"] = 0.0, 0.0, 1.0
        bar.update(1)
    
    bar.close()
    
    if missing > 0:
        print(f"    Warning: {missing} tiles had IDs exceeding point count")
    
    if len(tiles) > 0:
        sample_ids = [t["id"] for t in tiles[:5]]
        print(f"    Sample IDs: {sample_ids}")


# ============================================================
# COLOR GENERATION
# ============================================================

def get_population_color(population: int, max_pop: int) -> Tuple[int, int, int]:
    """Map population value to a color gradient."""
    if max_pop == 0:
        return POPULATION_COLORS[0]
    
    # Normalize population to 0-1 range
    norm = min(1.0, population / max_pop)
    
    # Find which color segment
    segment_count = len(POPULATION_COLORS) - 1
    segment = norm * segment_count
    idx = int(segment)
    frac = segment - idx
    
    if idx >= segment_count:
        return POPULATION_COLORS[-1]
    
    # Interpolate between colors
    c1 = POPULATION_COLORS[idx]
    c2 = POPULATION_COLORS[idx + 1]
    
    return (
        int(c1[0] * (1 - frac) + c2[0] * frac),
        int(c1[1] * (1 - frac) + c2[1] * frac),
        int(c1[2] * (1 - frac) + c2[2] * frac)
    )


# ============================================================
# RENDERING
# ============================================================

def image_xy_to_sphere_batch(width: int, height: int) -> np.ndarray:
    """Generate sphere coordinates for all pixels."""
    print(f"\nGenerating pixel coordinates...")
    bar = ProgressBar(height, "  Building coordinate grid")
    
    x_img = np.arange(width)
    y_img = np.arange(height)
    xx, yy = np.meshgrid(x_img, y_img)
    bar.update(height)
    bar.close()
    
    print("  Converting to sphere coordinates...")
    lon = (xx / width) * 360.0 - 180.0
    lat = 90.0 - (yy / height) * 180.0
    
    lat_rad = np.radians(lat)
    lon_rad = np.radians(lon)
    
    y = np.sin(lat_rad)
    r = np.cos(lat_rad)
    x = np.cos(lon_rad) * r
    z = np.sin(lon_rad) * r
    
    points = np.column_stack((x.ravel(), y.ravel(), z.ravel()))
    print(f"  Generated {len(points):,} points")
    return points

def render_world_fast(tiles: List[dict], metadata: dict):
    """Main rendering function."""
    print("\n" + "="*60)
    print(f"UNIFIED WORLD RENDERER - Mode: {RENDER_MODE}")
    print(f"Total tiles loaded: {len(tiles):,}")
    print("="*60)
    
    if not tiles:
        print("No tiles to render! Check RENDER_* flags.")
        return
    
    # Get base points from metadata or compute from max ID
    base_points = metadata.get("base_points", 0)
    if base_points == 0 and tiles:
        base_points = max(t["id"] for t in tiles) + 1
        print(f"\n  Base points inferred from max ID: {base_points:,}")
    
    print(f"\nBase resolution: {base_points:,} Fibonacci points")
    
    # Display tile counts by type
    type_counts = {}
    for tile in tiles:
        tile_type = tile.get("type", "unknown")
        type_counts[tile_type] = type_counts.get(tile_type, 0) + 1
    
    print(f"\nTile counts by type:")
    for tile_type, count in sorted(type_counts.items()):
        print(f"  {tile_type}: {count:,} tiles")
    
    # ID statistics
    all_ids = [t["id"] for t in tiles]
    print(f"\nID statistics:")
    print(f"  Min ID: {min(all_ids):,}")
    print(f"  Max ID: {max(all_ids):,}")
    print(f"  Actual tiles: {len(tiles):,}")
    
    # Regenerate positions
    print("\n" + "="*60)
    print("REGENERATING POSITIONS")
    print("="*60)
    regenerate_positions(tiles, base_points)
    
    # Build KD-tree
    print("\n" + "="*60)
    print("BUILDING KD-TREE")
    print("="*60)
    positions = np.array([[t["x"], t["y"], t["z"]] for t in tiles], dtype=np.float64)
    tree = cKDTree(positions)
    print(f"  KD-tree built with {len(positions):,} points")
    
    # Generate query points
    query_points = image_xy_to_sphere_batch(IMAGE_WIDTH, IMAGE_HEIGHT)
    
    # Batch query
    print("\n" + "="*60)
    print("QUERYING NEAREST TILES")
    print("="*60)
    query_bar = ProgressBar(len(query_points), "  KD-tree query", width=40)
    
    chunk_size = 1000000
    all_indices = []
    
    for i in range(0, len(query_points), chunk_size):
        chunk = query_points[i:i+chunk_size]
        distances, indices = tree.query(chunk, k=1)
        all_indices.extend(indices)
        query_bar.update(len(chunk))
    
    query_bar.close()
    indices = np.array(all_indices, dtype=np.int32)
    
    # Build color array based on render mode
    print("\n" + "="*60)
    print(f"BUILDING COLOR ARRAY (Mode: {RENDER_MODE})")
    print("="*60)
    
    if RENDER_MODE == "type":
        # Type-based rendering
        print(f"  Creating color lookup table for {len(tiles):,} tiles...")
        tile_colors = np.zeros((len(tiles), 3), dtype=np.uint8)
        
        color_bar = ProgressBar(len(tiles), "  Building color lookup")
        for i, tile in enumerate(tiles):
            tile_type = tile.get("type", "unknown")
            rgb = TYPE_COLORS.get(tile_type, TYPE_COLORS["unknown"])
            tile_colors[i] = rgb
            color_bar.update(1)
        color_bar.close()
        
        # Fast vectorized lookup
        print(f"  Applying colors to {len(indices):,} pixels...")
        img_array = tile_colors[indices]
        
    elif RENDER_MODE == "random":
        # Random colors based on tile ID
        max_id = max(t["id"] for t in tiles)
        print(f"  Creating random colors for IDs 0..{max_id:,}")
        
        random_bar = ProgressBar(max_id + 1, "  Generating random colors", width=40)
        
        rng = np.random.RandomState(42)
        random_colors = np.zeros((max_id + 1, 3), dtype=np.uint8)
        
        chunk = 100000
        for start in range(0, max_id + 1, chunk):
            end = min(start + chunk, max_id + 1)
            random_colors[start:end] = rng.randint(50, 256, size=(end - start, 3), dtype=np.uint8)
            random_bar.update(end - start)
        
        random_bar.close()
        
        # Build tile color lookup
        print(f"  Building tile color lookup...")
        tile_colors = np.zeros((len(tiles), 3), dtype=np.uint8)
        color_bar = ProgressBar(len(tiles), "  Mapping tile IDs to colors")
        
        for i, tile in enumerate(tiles):
            tile_colors[i] = random_colors[tile["id"]]
            color_bar.update(1)
        color_bar.close()
        
        # Apply to pixels
        print(f"  Applying colors to {len(indices):,} pixels...")
        img_array = tile_colors[indices]
    
    elif RENDER_MODE == "population":
        # Population-based gradient
        print(f"  Finding population range...")
        populations = [t.get("population", 0) for t in tiles]
        max_pop = max(populations) if populations else 1
        
        print(f"  Population range: 0 to {max_pop:,}")
        print(f"  Creating color lookup table...")
        
        tile_colors = np.zeros((len(tiles), 3), dtype=np.uint8)
        color_bar = ProgressBar(len(tiles), "  Building color lookup")
        
        for i, tile in enumerate(tiles):
            pop = tile.get("population", 0)
            rgb = get_population_color(pop, max_pop)
            tile_colors[i] = rgb
            color_bar.update(1)
        color_bar.close()
        
        # Apply to pixels
        print(f"  Applying colors to {len(indices):,} pixels...")
        img_array = tile_colors[indices]
    
    else:
        raise ValueError(f"Invalid render mode: {RENDER_MODE}")
    
    # Reshape to 2D image
    print("\n" + "="*60)
    print("CREATING FINAL IMAGE")
    print("="*60)
    print("  Reshaping to 2D...")
    img_array = img_array.reshape(IMAGE_HEIGHT, IMAGE_WIDTH, 3)
    
    print("  Creating PIL image...")
    image = Image.fromarray(img_array, "RGB")
    
    print(f"  Saving {OUTPUT_FILE}...")
    image.save(OUTPUT_FILE)
    
    print("\n" + "="*60)
    print("✓ RENDER COMPLETE!")
    print(f"  Output: {OUTPUT_FILE}")
    print(f"  Size: {IMAGE_WIDTH}x{IMAGE_HEIGHT}")
    print("="*60)


# ============================================================
# MAIN
# ============================================================

def main():
    print("="*60)
    print("UNIFIED WORLD RENDERER")
    print("Works with single-file output from new generator")
    print("="*60)
    
    start_time = time.time()
    
    tiles, metadata = load_tiles()
    if not tiles:
        print("\nNo tiles loaded!")
        print("Make sure:")
        print("  1. tiles_static.json exists")
        print("  2. tiles_metadata.json exists")
        print("  3. RENDER_* flags are set correctly")
        return
    
    render_world_fast(tiles, metadata)
    
    elapsed = time.time() - start_time
    print(f"\nTotal time: {elapsed:.1f} seconds")


if __name__ == "__main__":
    main()