"""
Reads from single static/dynamic files generated by the generator.
Renders based on terrain type.
"""

import json
import math
import struct
import base64
import time
import numpy as np
from PIL import Image
from scipy.spatial import cKDTree
from typing import List, Dict, Tuple, Optional


# ============================================================
# PROGRESS BAR
# ============================================================

class ProgressBar:
    def __init__(self, total: int, desc: str = "Progress", width: int = 50):
        self.total = total
        self.desc = desc
        self.width = width
        self.current = 0
        self.start_time = time.time()
        self.last_print = 0
        
    def update(self, n: int = 1):
        self.current += n
        if self.current - self.last_print >= max(1, self.total // 100) or self.current >= self.total:
            self.print_bar()
            self.last_print = self.current
    
    def print_bar(self):
        percent = self.current / self.total if self.total > 0 else 1
        filled = int(self.width * percent)
        bar = "█" * filled + "░" * (self.width - filled)
        
        elapsed = time.time() - self.start_time
        if percent > 0 and percent < 1:
            eta = elapsed / percent - elapsed
            eta_str = f"ETA: {eta:.1f}s"
        else:
            eta_str = "Done!    "
        
        print(f"\r{self.desc}: |{bar}| {percent*100:5.1f}% ({self.current:,}/{self.total:,}) {eta_str}", end="", flush=True)
        
        if self.current >= self.total:
            print()
    
    def close(self):
        if self.current < self.total:
            self.current = self.total
            self.print_bar()


# ============================================================
# CONFIGURATION
# ============================================================

# Unified file names
STATIC_FILE = "tiles_static.json"
DYNAMIC_FILE = "tiles_dynamic.json"
METADATA_FILE = "tiles_metadata.json"

# Render settings
IMAGE_HEIGHT = 4096
IMAGE_WIDTH = IMAGE_HEIGHT * 2
RENDER_MODE = "random"  # "terrain" or "random"

if RENDER_MODE == "terrain":
    OUTPUT_FILE = "world_terrain.png"
elif RENDER_MODE == "random":
    OUTPUT_FILE = "world_random.png"
else:
    print("Incorrect RENDER_MODE - must be 'terrain' or 'random'")
    import sys
    sys.exit()

# Terrain colors (based on terrain type string from static data)
TERRAIN_COLORS = {
    "": (89, 89, 89),           # Default/empty
    "mountain": (139, 90, 43),  # Brown
    "hill": (160, 120, 60),     # Light brown
    "flat": (180, 180, 100),    # Pale yellow-green
    "forest": (34, 139, 34),    # Forest green
    "desert": (238, 210, 170),  # Sand
    "swamp": (85, 107, 47),     # Dark olive green
    "tundra": (200, 200, 200),  # Light gray
    "ice": (240, 248, 255),     # Ice blue
    "water": (25, 25, 112),     # Deep blue
    "coastal": (135, 206, 235), # Sky blue
    "unknown": (89, 89, 89)     # Gray
}


# ============================================================
# UTILITIES
# ============================================================

def decode_neighbors(encoded: str) -> list:
    """Decode base64 encoded neighbors."""
    if not encoded:
        return []
    binary = base64.b64decode(encoded)
    count = len(binary) // 4
    return list(struct.unpack(f"<{count}I", binary))

def load_tiles() -> Tuple[List[dict], dict]:
    """Load all tiles from unified files."""
    print("Loading unified tile files...")
    
    # Load metadata first
    try:
        with open(METADATA_FILE, "r") as f:
            metadata = json.load(f)
        print(f"  Metadata loaded:")
        print(f"    Total tiles: {metadata.get('total_tiles', 0):,}")
        print(f"    Base points: {metadata.get('base_points', 0):,}")
        print(f"    Neighbor count: {metadata.get('neighbor_count', 0)}")
    except FileNotFoundError:
        print(f"  Warning: {METADATA_FILE} not found")
        metadata = {}
    except json.JSONDecodeError:
        print(f"  Warning: {METADATA_FILE} is corrupted")
        metadata = {}
    
    # Load static data
    try:
        with open(STATIC_FILE, "r") as f:
            static_data = json.load(f)
        print(f"  Loaded {len(static_data):,} tiles from {STATIC_FILE}")
    except FileNotFoundError:
        print(f"  ERROR: {STATIC_FILE} not found")
        return [], {}
    except json.JSONDecodeError:
        print(f"  ERROR: {STATIC_FILE} is corrupted")
        return [], {}
    
    # Load dynamic data
    try:
        with open(DYNAMIC_FILE, "r") as f:
            dynamic_data = json.load(f)
        print(f"  Loaded {len(dynamic_data):,} entries from {DYNAMIC_FILE}")
    except FileNotFoundError:
        print(f"  Warning: {DYNAMIC_FILE} not found, using defaults")
        dynamic_data = []
    except json.JSONDecodeError:
        print(f"  Warning: {DYNAMIC_FILE} is corrupted, using defaults")
        dynamic_data = []
    
    # Build dynamic lookup
    dyn_lookup = {item["id"]: item for item in dynamic_data}
    
    # Combine static and dynamic data
    tiles = []
    
    bar = ProgressBar(len(static_data), "  Loading tiles")
    
    for s in static_data:
        tid = s["id"]
        d = dyn_lookup.get(tid, {})
        
        tiles.append({
            "id": tid,
            "neighbors": decode_neighbors(s.get("neighbors_b64", "")),
            "temperature": s.get("temperature", ""),
            "precipitation": s.get("precipitation", ""),
            "terrain": s.get("terrain", ""),
            "vegetation": d.get("vegetation", ""),
            "population": d.get("population", 0),
            "buildings": d.get("buildings", [])
        })
        bar.update(1)
    
    bar.close()
    
    # Sort by ID for consistent ordering
    tiles.sort(key=lambda t: t["id"])
    
    print(f"\n  Loaded {len(tiles):,} tiles")
    
    # Display terrain type counts
    terrain_counts = {}
    for tile in tiles:
        terrain = tile.get("terrain", "")
        terrain_counts[terrain] = terrain_counts.get(terrain, 0) + 1
    
    if terrain_counts:
        print(f"\n  Terrain distribution:")
        for terrain, count in sorted(terrain_counts.items(), key=lambda x: -x[1])[:10]:
            print(f"    '{terrain}': {count:,} tiles")
    
    return tiles, metadata


# ============================================================
# FIBONACCI SPHERE & POSITIONS
# ============================================================

def fibonacci_sphere(samples: int) -> np.ndarray:
    """Generate Fibonacci sphere points as numpy array."""
    phi = (1 + math.sqrt(5)) / 2
    golden_angle = 2 * math.pi / phi
    i = np.arange(samples)
    y = 1 - (2*i + 1) / samples
    radius = np.sqrt(1 - y*y)
    theta = golden_angle * i
    x = np.cos(theta) * radius
    z = np.sin(theta) * radius
    return np.column_stack((x, y, z))

def regenerate_positions(tiles: List[dict], total_points: int):
    """Regenerate positions for all tiles."""
    if not tiles:
        return
    
    print(f"  Regenerating positions for {len(tiles):,} tiles...")
    positions = fibonacci_sphere(total_points)
    
    bar = ProgressBar(len(tiles), "  Assigning positions")
    
    missing = 0
    for tile in tiles:
        idx = tile["id"]
        if idx < total_points:
            tile["x"], tile["y"], tile["z"] = positions[idx]
        else:
            missing += 1
            tile["x"], tile["y"], tile["z"] = 0.0, 0.0, 1.0
        bar.update(1)
    
    bar.close()
    
    if missing > 0:
        print(f"    Warning: {missing} tiles had IDs exceeding point count")
    
    if len(tiles) > 0:
        sample_ids = [t["id"] for t in tiles[:5]]
        print(f"    Sample IDs: {sample_ids}")


# ============================================================
# RENDERING
# ============================================================

def image_xy_to_sphere_batch(width: int, height: int) -> np.ndarray:
    """Generate sphere coordinates for all pixels."""
    print(f"\nGenerating pixel coordinates...")
    bar = ProgressBar(height, "  Building coordinate grid")
    
    x_img = np.arange(width)
    y_img = np.arange(height)
    xx, yy = np.meshgrid(x_img, y_img)
    bar.update(height)
    bar.close()
    
    print("  Converting to sphere coordinates...")
    lon = (xx / width) * 360.0 - 180.0
    lat = 90.0 - (yy / height) * 180.0
    
    lat_rad = np.radians(lat)
    lon_rad = np.radians(lon)
    
    y = np.sin(lat_rad)
    r = np.cos(lat_rad)
    x = np.cos(lon_rad) * r
    z = np.sin(lon_rad) * r
    
    points = np.column_stack((x.ravel(), y.ravel(), z.ravel()))
    print(f"  Generated {len(points):,} points")
    return points

def render_world_fast(tiles: List[dict], metadata: dict):
    """Main rendering function."""
    print("\n" + "="*60)
    print(f"WORLD RENDERER - Mode: {RENDER_MODE}")
    print(f"Total tiles loaded: {len(tiles):,}")
    print("="*60)
    
    if not tiles:
        print("No tiles to render!")
        return
    
    # Get base points from metadata or compute from max ID
    base_points = metadata.get("base_points", 0)
    if base_points == 0 and tiles:
        base_points = max(t["id"] for t in tiles) + 1
        print(f"\n  Base points inferred from max ID: {base_points:,}")
    
    print(f"\nBase resolution: {base_points:,} Fibonacci points")
    
    # ID statistics
    all_ids = [t["id"] for t in tiles]
    print(f"\nID statistics:")
    print(f"  Min ID: {min(all_ids):,}")
    print(f"  Max ID: {max(all_ids):,}")
    print(f"  Actual tiles: {len(tiles):,}")
    
    # Regenerate positions
    print("\n" + "="*60)
    print("REGENERATING POSITIONS")
    print("="*60)
    regenerate_positions(tiles, base_points)
    
    # Build KD-tree
    print("\n" + "="*60)
    print("BUILDING KD-TREE")
    print("="*60)
    positions = np.array([[t["x"], t["y"], t["z"]] for t in tiles], dtype=np.float64)
    tree = cKDTree(positions)
    print(f"  KD-tree built with {len(positions):,} points")
    
    # Generate query points
    query_points = image_xy_to_sphere_batch(IMAGE_WIDTH, IMAGE_HEIGHT)
    
    # Batch query
    print("\n" + "="*60)
    print("QUERYING NEAREST TILES")
    print("="*60)
    query_bar = ProgressBar(len(query_points), "  KD-tree query", width=40)
    
    chunk_size = 1000000
    all_indices = []
    
    for i in range(0, len(query_points), chunk_size):
        chunk = query_points[i:i+chunk_size]
        distances, indices = tree.query(chunk, k=1)
        all_indices.extend(indices)
        query_bar.update(len(chunk))
    
    query_bar.close()
    indices = np.array(all_indices, dtype=np.int32)
    
    # Build color array based on render mode
    print("\n" + "="*60)
    print(f"BUILDING COLOR ARRAY (Mode: {RENDER_MODE})")
    print("="*60)
    
    if RENDER_MODE == "terrain":
        # Terrain-based rendering
        print(f"  Creating color lookup table for {len(tiles):,} tiles...")
        tile_colors = np.zeros((len(tiles), 3), dtype=np.uint8)
        
        color_bar = ProgressBar(len(tiles), "  Building color lookup")
        for i, tile in enumerate(tiles):
            terrain = tile.get("terrain", "")
            rgb = TERRAIN_COLORS.get(terrain, TERRAIN_COLORS["unknown"])
            tile_colors[i] = rgb
            color_bar.update(1)
        color_bar.close()
        
        # Fast vectorized lookup
        print(f"  Applying colors to {len(indices):,} pixels...")
        img_array = tile_colors[indices]
        
    elif RENDER_MODE == "random":
        # Random colors based on tile ID
        max_id = max(t["id"] for t in tiles)
        print(f"  Creating random colors for IDs 0..{max_id:,}")
        
        random_bar = ProgressBar(max_id + 1, "  Generating random colors", width=40)
        
        rng = np.random.RandomState(42)
        random_colors = np.zeros((max_id + 1, 3), dtype=np.uint8)
        
        chunk = 100000
        for start in range(0, max_id + 1, chunk):
            end = min(start + chunk, max_id + 1)
            random_colors[start:end] = rng.randint(50, 256, size=(end - start, 3), dtype=np.uint8)
            random_bar.update(end - start)
        
        random_bar.close()
        
        # Build tile color lookup
        print(f"  Building tile color lookup...")
        tile_colors = np.zeros((len(tiles), 3), dtype=np.uint8)
        color_bar = ProgressBar(len(tiles), "  Mapping tile IDs to colors")
        
        for i, tile in enumerate(tiles):
            tile_colors[i] = random_colors[tile["id"]]
            color_bar.update(1)
        color_bar.close()
        
        # Apply to pixels
        print(f"  Applying colors to {len(indices):,} pixels...")
        img_array = tile_colors[indices]
    
    else:
        raise ValueError(f"Invalid render mode: {RENDER_MODE}")
    
    # Reshape to 2D image
    print("\n" + "="*60)
    print("CREATING FINAL IMAGE")
    print("="*60)
    print("  Reshaping to 2D...")
    img_array = img_array.reshape(IMAGE_HEIGHT, IMAGE_WIDTH, 3)
    
    print("  Creating PIL image...")
    image = Image.fromarray(img_array, "RGB")
    
    print(f"  Saving {OUTPUT_FILE}...")
    image.save(OUTPUT_FILE)
    
    print("\n" + "="*60)
    print("✓ RENDER COMPLETE!")
    print(f"  Output: {OUTPUT_FILE}")
    print(f"  Size: {IMAGE_WIDTH}x{IMAGE_HEIGHT}")
    print("="*60)


# ============================================================
# MAIN
# ============================================================

def main():
    print("="*60)
    print("WORLD RENDERER")
    print("Renders terrain-based tiles")
    print("="*60)
    
    start_time = time.time()
    
    tiles, metadata = load_tiles()
    if not tiles:
        print("\nNo tiles loaded!")
        print("Make sure:")
        print("  1. tiles_static.json exists")
        print("  2. tiles_metadata.json exists")
        return
    
    render_world_fast(tiles, metadata)
    
    elapsed = time.time() - start_time
    print(f"\nTotal time: {elapsed:.1f} seconds")


if __name__ == "__main__":
    main()